### ISSUE TITLE
Conflict with GoPanel

### ISSUE THREAD

**Issue by dvanw6** [chsh2/nijiGPen#44]
I've been using GoPanel for a while, and I installed NijiGpen last night, today as I've gone to do some work, I've found my GoPanel doesnt work anymore, and I get this error:

_Python: Traceback (most recent call last):
  File "C:\Users\dvanw6\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\go_panel\utils\check_updates.py", line 134, in execute
    check_updates()
  File "C:\Users\dvanw6\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\go_panel\utils\check_updates.py", line 44, in check_updates
    addon_version = [addon.bl_info.get('version', (-1,-1,-1)) for addon in addon_utils.modules() if addon.bl_info['name'] == friendly_name][0]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range_

I attempted to uninstall it, but GoPanel continues to be broken giving me this error:

_Python: Traceback (most recent call last):
  File "C:\Users\dvanw6\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\go_panel\operators\switch_tool.py", line 141, in execute
    raise ValueError("Invalid format for tool string")
ValueError: Invalid format for tool string_

Note that it was all fine right before I installed NijiGpen

**Comment by chsh2** [comment]
Could you please also report this issue to the GoPanel developers? The message indicates that the error happens in their code, which is not public and I do not have access to it. However, they can check my add-on's code and may be able to solve this problem better than I can.

Besides, according to the message, it looks like the error happens during GoPanel updates itself. From the introduction video, I see there is an option "Auto-check for Update":
![](https://github.com/user-attachments/assets/234a204e-eece-4a3c-ad63-8ee9b69d754f)

Could you try to disable it and see if the error still exists?

**Comment by dvanw6** [comment]
I've talked with the GoPanel devs, I was able to get things fixed, part of the issue seems to be on Blender's side which was causing errors with any shortcut that used the numpad. 
They have just issued an update to fix the Check for Updates error, but why my numpad shortcuts broke after using NijiGpen I have no idea.
I reset up all my shortcuts to use the top row numbers (ctrl alt 1, 2 3, etc) so it should hopefully not happen anymore. Ill attempt to use NijiGpen again, but on a different blender version, as I cant afford to break it again since I need it for work.
(If you're curious why I have shortcuts set up like this, its because I use a Tourbox to activate them, so key positioning doesnt matter).

Theres a good chance this whole error was just because of the numpad, it seems to be something that breaks often, even though this was a first time for me.

**Comment by chsh2** [comment]
Thank you for the information. I never tried to set a shortcut to the numpad so I did not know that Blender has issues with it. I will pay attention to this topic in the future.
